fn main() {

    panic!("A macro panic! força um erro irrecuperável");
    
}
